### ISSUE TITLE
Support for maximumBatchingWindowInSeconds in table.onEvent method

### ISSUE THREAD

**Issue by jimjoes** [pulumi/pulumi-awsx#1013]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be nice if the `table.onEvent` method allowed the setting of the `maximumBatchingWindowInSeconds` parameter as well as the `batchSize` parameter.

**Comment by rquitales** [comment]
@jimjoes Thanks for filing this feature request.

To clarify my understanding, could you please describe where this method is coming from and what you're trying to achieve since I lack the context to understand your request.

My brief search seems to indicate that this functionality already exists? Example Typescript code:

```
const dbTable = new aws.dynamodb.Table("main", {
    billingMode: "PAY_PER_REQUEST",
    hashKey: "who",
    attributes: [
        { name: "who", type: "S" },
    ]
});

dbTable.onEvent(
    "notify-on-new-message",
    evt => {
        console.log("event", JSON.stringify(evt));
        return;
    },
    { batchSize: 100, startingPosition: "LATEST",  maximumBatchingWindowInSeconds: 10}
);
```

Is this what you're trying to achieve?

**Comment by thomas11** [comment]
Closing this issue since we didn't receive a response. Feel free to re-open if necessary.
