### ISSUE TITLE
Add upgrade tests

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-awsx#1108]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add tests to validate behavior of existing resources as they are upgraded between versions, especially major version changes. Tests should target the key components prioritized by popularity and usage.

- [x] awsx:cloudtrail:Trail
- [x] awsx:ec2:DefaultVpc
- [x] awsx:ec2:Vpc
- [ ] awsx:ecs:EC2Service
- [ ] awsx:ecs:EC2TaskDefinition
- [x] awsx:ecs:FargateService
- [x] awsx:ecs:FargateTaskDefinition
- [x] awsx:ecr:Repository
- [x] ~awsx:ecr:Image~ (skipped - it created no resources in v1 but creates docker:Image in v2)
- [x] awsx:lb:ApplicationLoadBalancer
- [x] awsx:lb:NetworkLoadBalancer
- [x] awsx:lb:TargetGroupAttachment

**Comment by joeduffy** [comment]
Adding P1 since we already shipped and we want to get ahead of any version/upgrade issues before folks find them in the wild. Ideally this would be done today or worst case tomorrow.

**Comment by t0yv0** [comment]
I'm working on this but having some trouble recording these locally.

```
  aws:ecs:Service (my-service):
    error: 1 error occurred:
        * creating urn:pulumi:p-it-antons-mac-ts-lb-simp-9c5cbaf2::ts-lb-simple::awsx:ecs:FargateService$aws:ecs/service:Service::my-service: 1 error occurred:
        * waiting for ECS service (arn:aws:ecs:us-west-2:616138583583:service/default-cluster-215dd5f/my-service-4ab513f) to reach steady state after creation: timeout while waiting for state to become 'tfSTABLE' (last state: 'tfPENDING', timeout: 20m0s)
```

Will retry this one.

Also finding that some examples slightly changed to use new features so they can't be recorded on baseline version as-is, this is hopefully as expected.

```
		// Skipping because it does not work on pre-2.x versions, so upgrade tests cannot run.
		// "ts-vpc-getDefaultVpc",  // Property 'vpc' does not exist
		// "ts-ecr-simple",
```

**Comment by thomas11** [comment]
> Adding P1 since we already shipped and we want to get ahead of any version/upgrade issues before folks find them in the wild. Ideally this would be done today or worst case tomorrow.

I upgraded every test case in `examples` manually. Unless we add new test cases, automating the test won't surface any unknown issues at this point.

**Comment by mikhailshilkov** [comment]
We added upgrade tests based on Node.js programs in order to reuse the existing test suite. We learned that current upgrade testing framework is not hermetic for invokes: invokes are still executed against the cloud at preview time, as opposed to relying on snapshots. This makes the tests brittle: they have to be executed in the same environment as the snapshots were recorded (so that e.g. VPCs match up). We will follow-up with enhancements in providertests to improve that.

We got to green tests that cover most AWSX resources (9/12 resource types), except the ones below:
- ecr:Image.  In AWSX 1.0, the resource is an empty component resource. It was refactored from a function call in Docker V3 to using a custom resource in Docker V4. Upgrade test highlights this diff, but this is expected.
- ecs:EC2Service and ecs:EC2TaskDefinition aren't covered by existing tests. These resources are barely used though, <0.5% of all AWSX usage based on metabase query, so I think it's okay to skip them for now.

With this work merged, I'll go ahead and close the issue as done.
