### ISSUE TITLE
Permanent diff

### ISSUE THREAD

**Issue by aeweda** [pulumi/pulumi-awsx#1386]
### What happened?

i'm facing an issue that's driving me a bit insane, everytime i do a preview or an update all my ecs clusters are marked as changed, specifically task definitions & container definition

i had this issue before but it was contained to container env vars and i was gonna fix it by implementing a deep sort however now it's global

the problem is persistent in ci,local

### Example

```diff
- Command          : [
-     [0]: "sleep"
-     [1]: "60"
]
- Cpu              : 0
- DependsOn        : [
-     [0]: {
        - Condition    : "START"
        - ContainerName: "gateway"
    }
]
- Environment      : []
- Essential        : false
- Image            : "alpine:latest"
- LogConfiguration : {
    - LogDriver    : "awslogs"
    - Options      : {
        - awslogs-group        : "rx-b6b2f05"
        - awslogs-region       : "us-east-2"
        - awslogs-stream-prefix: "x"
    }
    - SecretOptions: <null>
}
- MemoryReservation: 65
- MountPoints      : []
- Name             : "x"
- PortMappings     : []
- SystemControls   : []
- VolumesFrom      : []
+ command          : [
+     [0]: "sleep"
+     [1]: "60"
]
+ cpu              : 0
+ dependsOn        : [
+     [0]: {
        + condition    : "START"
        + containerName: "gateway"
    }
]
+ environment      : []
+ essential        : false
+ image            : "alpine:latest"
+ logConfiguration : {
    + logDriver: "awslogs"
    + options  : {
        + awslogs-group        : "rx-b6b2f05"
        + awslogs-region       : "us-east-2"
        + awslogs-stream-prefix: "x"
    }
}
+ memoryReservation: 65
+ mountPoints      : []
+ name             : "x"
+ portMappings     : []
+ volumesFrom      : []
```

### Output of `pulumi about`

```
CLI          
Version      3.134.1
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME     VERSION
resource  aws      6.52.0
resource  awsx     2.16.0
resource  command  1.0.1
resource  docker   4.5.6
resource  docker   3.6.1
language  nodejs   unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/home/x/nvm/versions/node/v20.12.2/bin/node' version='v20.12.2'
```

### Additional context

i checked on AWS itself and the task definition is stored as `camelCase` as it should be, idk why pulumi is comparing with a downstream of `PascalCase`

also i tried switching to `pulumi-aws` instead of `awsx` yet the same problem persisted, i should also mention this problem did not happen 2 days ago

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
I'm sorry this is not working as expected!  There are some subtleties like https://github.com/pulumi/pulumi-aws/issues/4336 where we're normalization logic is not quite complete, we've been working with the upstream provider (Terraform AWS provider) to get this to work better. Unfortunately to make progress on this our team needs a very specific self-contained repro. If you could provide this it would be greatly appreciated!

**Comment by t0yv0** [comment]
Thank you!

**Comment by flostadler** [comment]
Hey @aeweda, I wasn't able to trigger a perma-diff with the repro you provided. Is there any additional steps/setups needed to trigger this?

**Comment by flostadler** [comment]
Ah ok @aeweda, yes I can reproduce the pascal case vs camel case issue now but not the perma-diff.
Let's tackle the two separately.

Cloudformation uses pascal case (generally, not only for this resource), but we're integrating with the AWS APIs directly. [`RegisterTaskDefinition`](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RegisterTaskDefinition.html) shows the props in camel case, so that should be correct.
What's interesting is that this behavior doesn't trigger on a slimmed down example, so it seems like a specific setting is tripping up the normalization logic.
I'll dig deeper to find the root cause for that.

I understand that it's hard to further debug the perma diff on your end with 60 different clusters. Let me know if you have any observations or a hunch what could trigger it, otherwise I'll first focus on getting the pascal case vs camel case diff issue resolved.

**Comment by flostadler** [comment]
Quick update from my end, I'm still working on finding the root cause for the capitalization issue but couldn't pin point it yet. I'll keep you posted with my findings

**Comment by flostadler** [comment]
@aeweda I wasn't yet able to find the root cause of the capitalization issue. I have a suspicion that this behavior is inherited from the upstream terraform provider of the underlying pulumi aws classic provider, but wasn't yet able to reproduce it with the aws classic provider itself. It might be the normalization logic [here](https://github.com/hashicorp/terraform-provider-aws/blob/1cc738f52986269b01eafe3a6cd34656160646cd/internal/service/ecs/task_definition.go#L81-L111) that's causing it, but I don't yet have an explanation as to why it would lead to the capitalization problems.

**Comment by ringods** [comment]
@flostadler @t0yv0 Referring to the repro I sent via our internal Slack, here is the `pulumi about` output for my repro:

```sh
pulumi about
CLI          
Version      3.137.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.57.0
resource  awsx    2.16.1
resource  docker  4.5.7
resource  docker  3.6.1
language  nodejs  unknown

Host     
OS       darwin
Version  15.1
Arch     arm64

This project is written in nodejs: executable='/Users/ringods/.volta/bin/node' version='v20.17.0'

<redacted list of resources>

Found no pending operations associated with team-ce/ringo

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/v-ringo-pulumi-corp
User           v-ringo-pulumi-corp
Organizations  v-ringo-pulumi-corp, team-ce
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/aws     6.57.0
@pulumi/awsx    2.16.1
@pulumi/pulumi  3.137.0
@types/node     18.19.64
typescript      5.6.3
```
