### ISSUE TITLE
Compute the number of allowed AZs based on the target region

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-awsx#21]
Today, we restrict `numberOfAvailabilityZones` to be between 1 and 4.  In practice though, this limit is dependent on the target region.  We could look this up and use that as the limit instead to get a better early error (the user will still get an error eventually if they exceed the number of AZs in the region).

**Comment by CyrusNajmabadi** [comment]
There are two ways we can do this:

1. Have a hardcoded list per region that we maintain, or:
2. Dynamically determine this using a terraform-function

The latter would be nicer, but has a significant problem with how we currently structure our sdk.  Namely, to use the terraform-functions we have to be async.  But we need to know the `numberOfAvailabilityZones` synchronously because we use it up front to determine so many component/custom resources we create.

We could try to make these functions synchronous (through the user of an awful nodejs native hack that would allow us to block on hte async call), but otherwise we're SOL on '2'.

'1' is not terrible, but it's a big unpleasant as something we need to maintain.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/pulumi/pulumi-awsx/pull/278
