### ISSUE TITLE
CIDR mask calculation for subnets is off

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-awsx#275]
It appears the algorithm for splitting up CIDR blocks within subnets inside of a VPC might be wrong. The following program:

```typescript
import * as awsx from "@pulumi/awsx";
const vpc = new awsx.ec2.Vpc("my-vpc", {
    cidrBlock: "10.0.0.0/28",
});
```

yields the following error:

```
    error: Running program '/Users/joeduffy/temp/awsxplay' failed with an unhandled exception:
    Error: Cidr mask must be between "16" and "28" but was 30
        at VpcTopology.createSubnetsWorker (/Users/joeduffy/temp/awsxplay/node_modules/@pulumi/ec2/vpcTopology.ts:104:19)
        at VpcTopology.createSubnets (/Users/joeduffy/temp/awsxplay/node_modules/@pulumi/ec2/vpcTopology.ts:48:33)
        at new Vpc (/Users/joeduffy/temp/awsxplay/node_modules/@pulumi/ec2/vpc.ts:81:49)
        at Object.<anonymous> (/Users/joeduffy/temp/awsxplay/index.ts:4:13)
        at Module._compile (internal/modules/cjs/loader.js:689:30)
        at Module.m._compile (/Users/joeduffy/temp/awsxplay/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Object.require.extensions.(anonymous function) [as .ts] (/Users/joeduffy/temp/awsxplay/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    error: an unhandled error occurred: Program exited with non-zero exit code: 32
```

Putting in M23 just for an initial triage given the upcoming launch. I'll try a few other CIDR masks to see whether this happens anytime I venture outside of `/16` or whether it's more limited in scope (likely) to choosing an extreme like `28` which is the smallest range allowed.

**Comment by CyrusNajmabadi** [comment]
Ah, interesting.  This is by design, but could likely use better error messages.  here's the problem:

> https://aws.amazon.com/vpc/faqs/
>
> Q. Is there a limit on how large or small a subnet can be?
>
> The minimum size of a subnet is a /28 (or 14 IP addresses.) for IPv4. Subnets cannot be larger than the VPC in which they are created.

So you can't have smaller than a /28 subnet.  Now, here's what happens when you try to make:

```ts
new awsx.ec2.Vpc("my-vpc", {
    cidrBlock: "10.0.0.0/28",
});
```

First, this is equivalent to hte following:

```ts
new awsx.ec2.Vpc("my-vpc", {
    cidrBlock: "10.0.0.0/28",
    numberOfAvailabilityZones: 2,
    subnets: [
        { type: "public" },
        { type: "private" },
    ],
});
```

So, given the number of AZs and the default split for subnets, this means we're going to try to split the actual amount of IP addresses in your cidr region by `two AZs * two subnets = 4 total subnet regions`.

Now, because you picked `10.0.0.0/28`, that means you only have 16 *total* IPs.  And trying to make 4 subnets out of that will give you 4 IPs per subnet.  That's far below the allowable amount.  

Now, if you only really want one subnet, you can do that by calling:


```ts
new awsx.ec2.Vpc("my-vpc", {
    cidrBlock: "10.0.0.0/28",
    numberOfAvailabilityZones: 1,
    subnets: [
        { type: "private" },
    ],
});
```

This will actually work but you'll only end up with one subnet.

**Comment by CyrusNajmabadi** [comment]
I'm going to add a better error message here to help track down this down.

**Comment by CyrusNajmabadi** [comment]
With my change, you'll get this error:

```
Error: Not enough address space in VPC to create desired subnet config.
VPC has 16 IPs, but is being asked to split into a total of 2 subnets.
2 subnets are necessary to have 2 AZ(s) each with 1 subnet(s) in them.
This needs 8 IPs/subnet, which is smaller than the minimum (16) allowed by AWS.
```

**Comment by joeduffy** [comment]
This is great, thanks for the quick deep dive into this.

**Comment by CyrusNajmabadi** [comment]
> or whether it's more limited in scope (likely) to choosing an extreme like 28 which is the smallest range allowed.

it's basically limited by needing to have no less than 16ips per subnet.  So, as you go narrower, our default AZ/subnet split is no longer good, and you have to be more explicit about how you want to break things up.  If you really do pick `/28` you can only have one subnet.  This means no AZ spreading, and no automatic public/private partition on your behalf.  because of the default of '2' and the defualt of a public/private split.  That means the min size address space we can handle is `64 = 2az * 2 partition * 16 minsize`.  So with 64 you colud only write `"10.0.0.0/26"` without needing to override some other value.
