### ISSUE TITLE
Make it easier for VPCs to use all availability zones

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-awsx#276]
It would be nice if `numberOfAvailabilityZones` automatically used the number of AZs in my current region, or at least offered the option to do so.

Unfortunately, because this is a `number`, doing so manually requires a bit of async tedium:

```typescript
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

module.exports = (async () => {
    const azs = await aws.getAvailabilityZones();
    const vpc = new awsx.ec2.Vpc("my-vpc", {
        numberOfAvailabilityZones: azs.names.length,
    });
    return {
        vpcId: vpc.id,
    };
})();
```

This is certainly not impossible, but any of the following would have been much nicer:

_*Option 1.* Automatically use all AZs by default.

```typescript
import * as awsx from "@pulumi/awsx";
const vpc = new awsx.ec2.Vpc("my-vpc");
export vpcId = vpc.id;
```

_*Option 2.* Accept an `auto`  parameter for `numberOfAvailabilityZones` (opt in).

```typescript
import * as awsx from "@pulumi/awsx";
const vpc = new awsx.ec2.Vpc("my-vpc", { numberOfAvailabilityZones: "auto" });
export vpcId = vpc.id;
```

_*Option 3.* Accept a `Promise<number>` for `numberOfAvailabilityZones`.

```typescript
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";
const vpc = new awsx.ec2.Vpc("my-vpc", {
    numberOfAvailabilityZones: aws.getAvailabilityZones().then(az => az.names.length),
});
export vpcId = vpc.id;
```

**Comment by CyrusNajmabadi** [comment]
This is hard.  THe main issue is that we need the az info in order to create resources (i.e. it affects the subnets we create).  Thus, we need to be able to call into our provider functions to do this.  Which makes VPC constructoin async, which makes thigns *hard* and has a lot of downstream effects.  

If we can make getAvailabilityZones sync (and i think we can), then this becomes much nicer.
