### ISSUE TITLE
Error creating Security Group: InvalidParameterValue: Value (sg-86c8964) for parameter GroupName is invalid.

### ISSUE THREAD

**Issue by crucialfelix** [pulumi/pulumi-awsx#328]
Default naming construction needs to omit the `-`

```
const sg = new awsx.ec2.SecurityGroup("sg", { vpc });
```

Diagnostics:
  aws:ec2:SecurityGroup (sg):
    error: Plan apply failed: Error creating Security Group: InvalidParameterValue: Value (sg-86c8964) for parameter GroupName is invalid. Group names may not be in the format sg-*.
    	status code: 400, request id: 5de30d96-b590-4e6c-9493-e27e1aed9486

Thanks! Great so far.

**Comment by crucialfelix** [comment]
btw. the ec2 SecurityGroup docs seems to be copypasted from terraform: https://pulumi.io/reference/pkg/nodejs/pulumi/aws/ec2/#SecurityGroup

> NOTE on Security Groups and Security Group Rules: Terraform currently provides both a standalone Security Group Rule resource

**Comment by joeduffy** [comment]
This seems to only happen if you name your security group `sg`, and is an unfortunate byproduct of how we auto-append a random suffix to help to avoid naming collisions.

One option would be to do eager verification in the constructor to check for this. That would have the benefit of failing during preview (rather than during the update, as the above will do), in addition to letting us give a better error message (since the user didn't add the suffix, it can be confusing at first).

**Comment by flostadler** [comment]
This issue refers to the previous version of awsx, now referred to as awsx-classic.

The current version of awsx does not include a `SecurityGroup` component anymore and awsx-classic will only receive updates for critical security fixes.
The good news is that awsx-classic is just copy&paste-able typescript code, so you can adapt it to your needs: https://github.com/pulumi/pulumi-awsx/tree/master/awsx-classic.
