### ISSUE TITLE
vpc.fromExistingIds returns empty private/public subnet ids

### ISSUE THREAD

**Issue by jchannon** [pulumi/pulumi-awsx#357]
Confirmed after speaking to @stack72 but the following code returns the vpc object but the private and public subnet id properties are empty.  I have not tested any other properties to see if they are empty.

```
const primaryVpc = awsx.ec2.Vpc.fromExistingIds("primary", {
    vpcId: "vpc-866580ff"
});
```

**Comment by CyrusNajmabadi** [comment]
@jchannon Yes, you would need to pass in the subnet ids here that you consider public/private/etc.

**Comment by jchannon** [comment]
But I’m querying using “fromExistingIds” to get back the subnet ids. I know
the vpc id that I want and I want it to return the other properties

**Comment by CyrusNajmabadi** [comment]
Hi @jchannon!  Right now, that's not a supported operation (primarily because we don't know which subnets you would consider your 'public' vs 'private' ones). The idea generally of the 'fromExisting' is that you know the IDs (because they were created outside of pulumi), and thus you can jsut pass in all that known data exactly as is without pulumi trying to guess at what is what. 

Thanks!

**Comment by jchannon** [comment]
Well I guess it ties this ties into here about knowing the type of subnet =
https://github.com/pulumi/pulumi-awsx/issues/358
