### ISSUE TITLE
Vpc.getSubnets('public') only returning 2 subnets 

### ISSUE THREAD

**Issue by c0bra** [pulumi/pulumi-awsx#403]
On my default Vpc I have 3 public subnets, one in each availability zone.

However when I attempt to get the subnets using `getSubnets('public')` only 2 are returned.

Example code:

```js
(async () => {
const vpc = awsx.ec2.Vpc.getDefault();
const existingSubnets = await vpc.getSubnets('public');
existingSubnets.forEach(x => pulumi.log.info('existingSubnet', x));
})()
```

**Comment by CyrusNajmabadi** [comment]
> On my default Vpc I have 3 public subnets, one in each availability zone.

Due to how earlier versions of pulumi worked, we hardcoded the numer of availability zones to 2.  We don't want to change that due to the deep implications it might have to other parts of the stack (since lots of code calls Vpc.getDefault()).

An option is to instead just do:

`const vpc = Vpc.fromExistingIds("default", { vpcId: yourVpcIde, publicSubnetIds: [...your ids...] })`

We coudl consider a config option to help control this.  It would need to be config vs an programattic option though so that all callers of this API would see the same value.

**Comment by c0bra** [comment]
I still don't think I quite understand but I'm going to chalk that up to my own density and not your explanation 😄

As long as there's a way for someone else using my infra code to produce the same result then it's fine AFAIK.

**Comment by joeduffy** [comment]
I just ran into this too and scratched my head, and spelunked in the code for a good hour, before stumbling across this bug. This behavior is definitely very confusing and I'm surprised we'd call this "by design." I believe we should change this behavior -- if I'm asking for the VPC's information, surely I would expect that publicSubnets accurately depicts the publicSubnets for that VPC?

If not, I'd add `getAllSubnets` or something but even then I'd worry it won't be discoverable and you'll need to get bitten by the surprising behavior before even knowing to go looking for it ...

**Comment by joeduffy** [comment]
FWIW, this is how it's manifesting for me. I'm trying to load balance across a set of VMs spread across the AZs in my region -- but the load balancer, because it uses the VPC machinery internally, is only load balancing across two of the three AZs ... This is actually a counter-example to the concern about this being a breaking change; we currently use this in a bunch of places that may be incorrectly limiting infrastructure to a subset of the intended AZs.

Here's the example, FWIW:

```typescript
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const ami = aws.getAmi({
    filters: [{ name: "name", values: ["amzn-ami-hvm-*-x86_64-ebs"] }],
    owners: [ "137112412989" ],
    mostRecent: true,
}).then(ami => ami.id);

const sg = new aws.ec2.SecurityGroup("web-secgrp", {
    ingress: [
        { protocol: "icmp", fromPort: 8, toPort: 0, cidrBlocks: ["0.0.0.0/0"] },
    ],
});

const alb = new awsx.lb.ApplicationLoadBalancer("web-traffic", {
    external: true,
    securityGroups: [ sg.id ],
});
const listener = alb.createListener("web-listener", { port: 80 });

export const ips: any[] = [];
export const hostnames: any[] = [];
for (const az of aws.getAvailabilityZones().names) {
    const server = new aws.ec2.Instance(`web-server-${az}`, {
        instanceType: "t2.micro",
        securityGroups: alb.securityGroups.map(sg => sg.securityGroup.name),
        ami: ami,
        availabilityZone: az,
        userData: "#!/bin/bash\n"+
            `echo 'Hello, World -- from ${az}!' > index.html\n` +
            "nohup python -m SimpleHTTPServer 80 &",
        tags: { "Name": "web-server" },
    });
    ips.push(server.publicIp);
    hostnames.push(server.publicDns);

    alb.attachTarget(`web-target-${az}`, server);
}

export const url = listener.endpoint.hostname;
```

**Comment by CyrusNajmabadi** [comment]
>  I believe we should change this behavior

This would break everyone using the existing code and would violate our "no breaking changes" philosophy.  

> but the load balancer, because it uses the VPC machinery internally, is only load balancing across two of the three AZs ... This is actually a counter-example to the concern about this being a breaking change; we currently use this in a bunch of places that may be incorrectly limiting infrastructure to a subset of the intended AZs.

Yes, but changing this will still break people.  For example, several computations we do are based on the number of azs we are considering.  For example, how we partition the subnet space.  If we go from partitioning from 2 to 3, for example, this won't be allowed as a change by aws.

--

Note: the general work to produce a better 'default vpc' abstraction, while not breaking people usin the existing one is tracked here: https://github.com/pulumi/pulumi-awsx/issues/350

Whatever we do, we need a way to ensure that users who are on the existing Vpc have a way (maybe opt-in or opt-out) to not be broken here.

**Comment by joeduffy** [comment]
> This would break everyone using the existing code and would violate our "no breaking changes" philosophy.

AWSX is not 1.0 for this very reason — because it isn't ready to be 1.0, and we are therefore willing to make breaking changes. Perhaps we can put this in the 1.0 upgrade?

**Comment by joeduffy** [comment]
also cc @lukehoban for his take -- this definitely reduced peoples' confidence in Pulumi during the recent workshops I was giving, especially since it wasn't obvious how to work around this.

**Comment by CyrusNajmabadi** [comment]
> AWSX is not 1.0 for this very reason — because it isn't ready to be 1.0, and we are therefore willing to make breaking changes. Perhaps we can put this in the 1.0 upgrade?

Just so i'm understanding.  If someone takes this route, it effectively means their pulumi app is basically broken and they tear down their existing stack and start all over again.  Are we really ok with that?

Vpcs are not in-place replacable.  Just making a subnet in a totally partitioned vpc space will simply error out.  That's the driving impetus for https://github.com/pulumi/pulumi-awsx/issues/350.

i.e. designing a new abstraction that can be used and which will have an actual story for migrating/mutating it over time.  

If we want to just break every stack that uses awsx today (and either instantiates a Vpc or uses `getDefault`), then this certainly gets easier.  But that's a *really* bitter pill to swallow IMO as that seems lke it will hit every customer.  The only ones not affected will be those that explicitly wrote `Vpc.fromExistingIds`.

**Comment by danielrbradley** [comment]
This has now been addressed with the new VPC component which defaults to 3 az's with the option to customise.
