### ISSUE TITLE
`Vpc.fromExistingIds` is very hard to use across stacks

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-awsx#522]
`Vpc.fromExistingIds` is the primary way to attempt to get an `awsx.ec2.Vpc` from existing resoruces.  But it requires that `publisSubnetIds` and `privateSubnetIds` be provided as arrays of `Inputs`.  In many/most cases, the user won't have a known array, they will just have an `Output<string[]>`.  For example, when getting these via `StackReference`, or from outputs of some other creation in the same Pulumi program.

We need to find a way to allow this to be used more flexibly.

The challenge is that internally `fromExistingIds` creates lots of `awsx.ec2.Something` resource - all of which are just virtual wrapper objects, and ultimately botttom out on `.get` calls.  But these would have to all be moved inside `apply` calls.  Doing so also may change the guarantee that we have prompt `publicSubnetIds` outputs on the `awsx.ec2.Vpc`, as we wouldn't even know how many there are until inputs are resolved.

This is a current workaround, but results in a `Output<Vpc>` instead of a `Vpc`, which will be harder to use in many use cases.

```ts
const vpcStack = new pulumi.StackReference("vpc");
const vpcId = vpcStack.getOutput("vpcId") as pulumi.Output<string>;
const publicSubnets = vpcStack.getOutput("publicSubnetIds") as pulumi.Output<string[]>;
const privateSubnets = vpcStack.getOutput("privateSubnetIds") as pulumi.Output<string[]>;

const vpc = pulumi.all([publicSubnets, privateSubnets]).apply(([publicSubnetIds, privateSubnetIds]) => {
    return awsx.ec2.Vpc.fromExistingIds("name", {
        vpcId,
        publicSubnetIds,
        privateSubnetIds,
    })    
});
```

**Comment by irshaam** [comment]
This is a workaround that results  in an out of Vpc instead of Output<Vpc>, which is easier to use in most cases . Can use as individual getSubnetIds method or just get the existing Vpc from the stack.

`const stack = new pulumi.StackReference(`vpcStack`);

const getVpcId = async (): Promise<string> => {
  const vpcId = await stack.getOutputValue(`vpcId`);
  return vpcId;
};


 const getPrivateSubnets = async (): Promise<string[]> => {
  const subnets: string[] = await stack.getOutputValue(`privateSubnetIds`);
  return subnets;
};

const getPublicSubnets = async (): Promise<string[]> => {
  const subnets: string[] = await stack.getOutputValue(`publicSubnetIds`);
  return subnets;
};

const getVpc = async (): Promise<awsx.ec2.Vpc> => {
  const vpcId = await getVpcId();
  const privateSubnetIds = await getPrivateSubnets();
  const publicSubnetIds = await getPublicSubnets();
  const vpc = awsx.ec2.Vpc.fromExistingIds('vpc', {
    vpcId,
    privateSubnetIds,
    publicSubnetIds,
  });

  return vpc;
};`

**Comment by danielrbradley** [comment]
Closing this as no-longer relevant after the 1.0.0 release. We no longer have the requirement to pass an instance of the VPC resource into other components, so there was no need to continue to support the `fromExistingIds` method, which therefore addresses this usability concern indirectly too.
