### ISSUE TITLE
Can't create PRIVATE awsx.apigateway.API

### ISSUE THREAD

**Issue by cabeaulac** [pulumi/pulumi-awsx#627]
I can't create a private API Gateway with Lambda binding.

When you deploy with this, you get an error that the deployment fails because there's not 
# Deploy PRIVATE APIGW fails
```
let endpoint = new awsx.apigateway.API(`ea-orders-${stackEnv}`, {
    
    restApiArgs: {
        endpointConfiguration: {
            types: "PRIVATE",
            vpcEndpointIds: [execApiVpcEndpointId],        
        },
    },
    
    routes: [{
        path: "/",
        method: "GET",
        eventHandler: async (event) => {
            // This code runs in an AWS Lambda and will be invoked any time `/` is hit.
            return {
                statusCode: 200,
                body: "hello",
            };
        },
    }],

},
);

```
# Workaround
If you add a RestApiPolicy, then the first deploy fails, because the policy isn't in place before the deployment runs. But running pulumi up a second time deploys the APIGW correctly because the Rest API Policy is in place now.
```
let endpoint = new awsx.apigateway.API(`ea-orders-${stackEnv}`, {
    
    restApiArgs: {
        endpointConfiguration: {
            types: "PRIVATE",
            vpcEndpointIds: [execApiVpcEndpointId],        
        },
    },
    
    routes: [{
        path: "/",
        method: "GET",
        eventHandler: async (event) => {
            // This code runs in an AWS Lambda and will be invoked any time `/` is hit.
            return {
                statusCode: 200,
                body: "hello",
            };
        },
    }],

},
);

const eaOrdersApiPolicy = new aws.apigateway.RestApiPolicy(`ea-orders-${stackEnv}`, {
    restApiId: endpoint.restAPI.id,
    policy: executeApiPolicy,
});
```
# Expected behavior
The ability to pass a RestApiPolicy to the API in restApiArgs or someplace. Yes, restApiArgs takes a policy argument, but it doesn't work for this purpose.

Thanks!

**Comment by leezen** [comment]
From what I can tell, this seems to be a problem with the underlying provider. When I specify the following:

```
let endpoint = new awsx.apigateway.API(`ea-orders`, {
    restApiArgs: {
        endpointConfiguration: {
            types: "PRIVATE",
        },
        policy: JSON.stringify({
            Version: "2012-10-17",
            Statement: [
                {
                    Effect: "Allow",
                    Principal: "*",
                    Action: "execute-api:Invoke",
                    Resource: ["execute-api:/*"],
                }
            ],
        }),
    },
    
    routes: [{
        path: "/",
        method: "GET",
        eventHandler: async (event) => {
            // This code runs in an AWS Lambda and will be invoked any time `/` is hit.
            return {
                statusCode: 200,
                body: "hello",
            };
        },
    }],


});
```

The first update fails when attempting to create the `Deployment` resource (the `RestApi` at this point exists, with the policy). Running a subsequent update succeeds. It appears to be a problem with the way `awsx` actually uses the underlying resource. `RestApi`'s `policy` property's doc states: "JSON formatted policy document that controls access to the API Gateway. This provider will only perform drift detection of its value when present in a configuration. It is recommended to use the `aws.apigateway.RestApiPolicy` resource instead" so I think since it's not initially present, it's not actually creating anything. I think this is fairly straightforward to address in the underlying implementation within awsx and will submit a PR.
